export const poData = {
  header: {
    logo: "Logo",
    company: {
      name: "Principal Manufacturing Corporation",
      address: "2800 South 19th Avenue",
      city: "Broadview, IL 60155",
      phone: "Tel 708-865-7500",
      fax: "Fax 708-865-7632",
    },
    poNumber: "156478224",
  },
  supplier: {
    name: "Metals USA Internation Company Ltd.",
    tradeName: "Metal USA",
    address: "N 115 W 18945 Drive",
    city: "Germantown, WI 53022",
    attention: {
      name: "Kushnier, Kyle",
      phone: "262-253-3818",
    },
  },
  shipTo: {
    name: "Principal Manufacturing Corporation.",
    address: "2800 S. 19th Ave",
    note: "(rear dock)",
    city: "Broadview, IL 60155",
  },
  poInfo: {
    poNo: "15657442",
    poDate: "10/15/2025",
    dueDate: "1/15/25",
    poRevision: "1/15/25",
    revisionDate: "1/15/25",
    orderedBy: "Fartred, Edward5",
    via: "Ground",
    pymtTerms: "Net 60",
    fob: "Origin",
    freightTerms: "Prepaid",
    note: "conf 8-5-54 52% NI ...>",
    routeTo: "XYZ",
  },
  items: [
    {
      item: "1:16",
      part: "A1376",
      desc: ".164 +/-.007 x 5.3750 +/-.005 x COIL Business",
      status: "Planned",
      date: "12/15/25",
      qty: "5,000",
      unit: "1.9863/lbs",
      ext: "9,931.50",
    },
    {
      item: "1:3",
      part: "",
      desc: "covers to 3-1-26",
      status: "Forecast",
      date: "1/5/26",
      qty: "21,000",
      unit: "1.9863/lbs",
      ext: "41,712.30",
    },
    { item: "1:4", part: "", desc: "", status: "Firm", date: "12/31/26", qty: "1", unit: "1.9863/lbs", ext: "1.99" },
    {
      item: "1:5",
      part: "B2387",
      desc: "Steel plate 2mm x 1000mm x 2000mm",
      status: "Planned",
      date: "1/10/26",
      qty: "500",
      unit: "2.5000/kg",
      ext: "1,250.00",
    },
    {
      item: "1:6",
      part: "C3498",
      desc: "Aluminum tube Aluminum tube  diameter Aluminum diameter Aluminum Aluminum tube  diameter Aluminum diameter Aluminum tube 25mm diameter x 3m length Aluminum Aluminum tube  diameter Aluminum diameter Aluminum tube 25mm diameter x 3m length Alumin tube  diameter Aluminum diameter Aluminum tube 25mm diameter x 3m length",
      status: "Forecast",
      date: "1/15/26",
      qty: "1,000",
      unit: "3.2500/m",
      ext: "3,250.00",
    },
    {
      item: "1:7",
      part: "D4509",
      desc: "Copper wire 5mm diameter insulated",
      status: "Firm",
      date: "1/20/26",
      qty: "2,500",
      unit: "1.7500/m",
      ext: "4,375.00",
    },
    {
      item: "1:8",
      part: "E5610",
      desc: "Stainless steel sheet 1.5mm x 1200mm x 2400mm",
      status: "Planned",
      date: "1/25/26",
      qty: "300",
      unit: "4.5000/kg",
      ext: "1,350.00",
    },
    {
      item: "1:9",
      part: "F6721",
      desc: "Brass rod 20mm diameter x 2m length 20mm diameter diameter x 2m length 20mm diameter x 2m len 20mm diameter x 2m length gth 20mm 20mm diameter x 2m length 20mm diameter x 2m length diameter x 2m length",
      status: "Forecast",
      date: "2/1/26",
      qty: "750",
      unit: "2.8000/m",
      ext: "2,100.00",
    },
    {
      item: "1:10",
      part: "G7832",
      desc: "Carbon fiber sheet 3mm x 500mm x 1000mm fiber sheet 3mm x 500mm x 1000mm 20mm diameter x 2m length",
      status: "Firm",
      date: "2/5/26",
      qty: "100",
      unit: "15.0000/sheet",
      ext: "1,500.00",
    },
    {
      item: "1:11",
      part: "H8943",
      desc: "Titanium plate 5mm x 600mm x 1200mm",
      status: "Planned",
      date: "2/10/26",
      qty: "50",
      unit: "25.0000/kg",
      ext: "1,250.00",
    },
    {
      item: "1:12",
      part: "I9054",
      desc: "Bronze bushing 30mm ID x 40mm OD x 50mm L",
      status: "Forecast",
      date: "2/15/26",
      qty: "2,000",
      unit: "1.2500/pc",
      ext: "2,500.00",
    },
    {
      item: "1:13",
      part: "J0165",
      desc: "Nickel ickel alloy w ickel alloy w alloy ickel alloy ickel alloy w w wire 3mm diameter",
      status: "Firm",
      date: "2/20/26",
      qty: "5,000",
      unit: "2.1000/m",
      ext: "10,500.00",
    },
    {
      item: "1:13",
      part: "J0165",
      desc: "Bronze bushing 30mm ID x 40mm OD x 50mm L Nickel ickel alloy Bronze bushing 30mm ID x 40mm OD x 50mm L 2mm x 500mm x 1000mm for radiation shielding Zinc Bronze bushing 30mm ID x 40mm OD x 50mm L",
      status: "Firm",
      date: "2/20/26",
      qty: "5,000",
      unit: "2.1000/m",
      ext: "10,500.00",
    },
    {
      item: "1:13",
      part: "J0165",
      desc: "Nickel ickel alloy w ickel alloy w alloy ickel alloy ickel alloy w w wire 3mm diameter",
      status: "Firm",
      date: "2/20/26",
      qty: "5,000",
      unit: "2.1000/m",
      ext: "10,500.00",
    },
    {
      item: "1:14",
      part: "K1276",
      desc: "Lead sheet 2mm x 500mm x 1000mm for radiation shielding Zinc coated sheet 0.8mm x 1000mm x 2000mm",
      status: "Planned",
      date: "2/25/26",
      qty: "400",
      unit: "3.7500/kg",
      ext: "1,500.00",
    },
    {
      item: "1:15",
      part: "L2387",
      desc: "Lead sheet 2mm x 500mm x 1000mm for radiation shielding",
      status: "Forecast",
      date: "3/1/26",
      qty: "200",
      unit: "8.5000/kg",
      ext: "1,700.00",
    },
    {
      item: "1:15",
      part: "L2387",
      desc: "Lead sheet 2mm x 500mm x 1000mm for radiation shielding",
      status: "Forecast",
      date: "3/1/26",
      qty: "200",
      unit: "8.5000/kg",
      ext: "1,700.00",
    },
    {
      item: "1:15",
      part: "L2387",
      desc: "Lead sheet 2mm x 500mm x 1000mm for radiation shielding",
      status: "Forecast",
      date: "3/1/26",
      qty: "200",
      unit: "8.5000/kg",
      ext: "1,700.00",
    },
    {
      item: "1:15",
      part: "L2387",
      desc: "Lead sheet 2mm x 500mm x 1000mm for radiation shielding",
      status: "Forecast",
      date: "3/1/26",
      qty: "200",
      unit: "8.5000/kg",
      ext: "1,700.00",
    },
  ],
  totals: {
    subTotalQty: "40,751",
    subTotalPrice: "88,957.29",
  },
  notes: {
    defaultNote: `AISI Alloy 304 CRS surface Finish Per SZM-20106 / ASTM A240 ANNEALED RB 92 MAX Change to LOW TACK WHITE 3MIL
PROTECTIVE FILM effective 10-14-22 Material free of pitting and scratches 20" ID 68" MAX O.D. MATERIAL CERTS WITH ROCKWELL
REQUIRED WITH ALL SHIPMENTS. CHEMICAL AND MECHANICAL CERTS REQUIRED WITH SHIPMENT.`,
    spotNC: `<p>Instructions to Supplier:</p> <p>This Purchase Order is subject to the PMC Terms and Conditions of Purchase.</p> <p>Unless this is a fixed-quantity contract under Section 2.1 of Principal Manufacturing Corporation Terms and
Conditions of Purchase (“T&C”) or expressly indicated otherwise, this Purchase Order is a requirements
contract under which Buyer is committing to purchase and Seller is committing to deliver 100% of Buyer’s
requirements. Specific quantities listed above may communicate release levels under a requirements contract
under Section 2.2 or 2.3 of the T&C. This Purchase Order incorporates and is governed exclusively by the T&C
effective as of the date of this Purchase Order, and for any renewals of this Purchase Order on the most recent
renewal date, which can be accessed at <a href="https://www.principalmfg.com/wp-content/uploads/Terms-Conditions-of">https://www.principalmfg.com/wp-content/uploads/Terms-Conditions-of</a>
Purchase-September-2025.pdf  or from Buyer’s purchasing representatives. It is expressly limited to its stated
terms, and Buyer rejects any additional or different terms proposed by Seller, which are not binding on Buyer
unless expressly agreed to by Buyer in writing. Subject to Buyer’s termination rights, this contract is binding for
the length of the applicable OEM vehicle program production life (including extensions and model refreshes as
determined by the OEM), and the service parts obligations that follow.</p> <p>For a copy of the PMC Supplier Manual.
</p> <a href="https://www.principalmfg.com/wp-content/uploads/Supplier-Manual-5.2-edition-PDF.pdf">https://www.principalmfg.com/wp-content/uploads/Supplier-Manual-5.2-edition-PDF.pdf</a>`,
    materialCertification: `<p>MATERIAL CERTIFICATION REQUIRED EACH SHIPMENT
</p> <p>Material certification shall specify the material conforms to blueprint raw 
material and declare the grade.</p>`,
    certificationRequired: `<p>A CERTIFICATION IS REQUIRED WITH EVERY SHIPMENT.</p>`,
    pmcReceivingHours: `<p>PMC will be closed for Thanksgiving November 27 and 28th 
RECEIVING HOURS WEEKDAYS 7 AM TO 3:30 PM</p>`,
    isoCompliance: `<p>PMC is ISO 14001 registered and all suppliers are required to comply with the 
handling of any substance of concern in a safe manner in accordance with 
applicable laws and regulations.</p>`,
    shippingInstructions: `<p>When shipping product through a common carrier to PMC, please use the following criteria:  Description: 
Unfinished Metal Stampings, Class:  50, NMFC:  104500.</p>`,
  },
};
